# Generated by Django 6.0.1 on 2026-04-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="access_code",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="share_token",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
