# Generated by Django 6.0.1 on 2026-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0003_quiz_access_code_quiz_share_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="pass_percentage",
            field=models.IntegerField(
                default=70, help_text="Minimum percentage to pass"
            ),
        ),
    ]
