# Generated by Django 6.0.1 on 2026-04-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0004_quiz_pass_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="security_answer_hash",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="security_question",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pet", "What was the name of your first pet?"),
                    ("city", "In what city were you born?"),
                    ("school", "What was the name of your first school?"),
                    ("mother_maiden", "What is your mother's maiden name?"),
                    ("favourite_teacher", "Who was your favourite teacher?"),
                    (
                        "childhood_friend",
                        "What is the name of your childhood best friend?",
                    ),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
